### ISSUE TITLE
Número de tarjeta

### ISSUE THREAD

**Issue by emmafauria** [PaulTOliver/fauria-rentacar#5]
Necesitamos también en la reserva poder poner número de la tarjeta de crédito del cliente. Dos campos: 
+ `....-....-....-....` (16 números separados por un guion)
+ `mm/yy` (fecha con solo mes y año)

**Comment by PaulTOliver** [comment]
Podemos incluir esta herramienta para validar que el número de tarjeta ingresado sea siempre válido:
https://github.com/jondavidjohn/payform

**Comment by PaulTOliver** [comment]
Esto ya esta listo! :+1: 

![Screenshot from 2019-04-06 21-35-23](https://user-images.githubusercontent.com/7141288/55674365-04d5f880-58b4-11e9-8505-e9032f56b285.png)
