### ISSUE TITLE
Carga de PDF en edición de clientes

### ISSUE THREAD

**Issue by emmafauria** [PaulTOliver/fauria-rentacar#6]
En la sección de edición de clientes hay un campo donde se puede adjuntar una imagen (ver debajo). En vez (o además) de una imagen queremos poder subir uno o varios archivos PDFs.

![Screenshot from 2019-04-03 21-09-18](https://user-images.githubusercontent.com/7141288/55506032-c5f63780-5654-11e9-908a-a5be00aa9ae6.png)

**Comment by PaulTOliver** [comment]
Listo! :+1:

![Screenshot from 2019-04-13 23-09-04](https://user-images.githubusercontent.com/7141288/56085324-51d04680-5e41-11e9-9704-2c65c9c58760.png)
